config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @events = Event.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h3>ユーザー情報一覧</h3>
 
<table>
  <thead>
    <tr>
      <th>H.N</th>
      <th>title</th>
      <th>難易度</th>
      <th>ストーリー</th>
      <th>満足度</th>
      <th>ひらめき</th>
      <th>意外性</th>
      <th>place</th>
      <th>体験日</th>
      <th>開始時間</th>
      <th>結果</th>
      <th>photo</th>
      <th>更新日</th>
      <th>作成日</th>
    </tr>
  </thead>
 
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.user.name %></td>
        <td><%= event.title %></td>
        <td><%= event.review_1 %></td>
        <td><%= event.review_2 %></td>
        <td><%= event.review_3 %></td>
        <td><%= event.review_4 %></td>
        <td><%= event.review_5 %></td>
        <td><%= event.place %></td>
        <td><%= event.play_day %></td>
        <td><%= event.start_time %></td>
        <td><%= event.result %></td>
        <td><%= event.event_image_url %></td>
        <td><%= event.updated_at %></td>
        <td><%= event.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<p><%= link_to "イベント新規登録", new_event_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EscapegameReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>